# Dockerfile for FastAPI
FROM python:3.11

WORKDIR /app

COPY ./fastapi_app/* .
RUN mkdir models

# RUN pip install --no-cache-dir -r requirements.txt 
RUN pip install -r requirements.txt 

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
