# Dockerfile for Streamlit
FROM python:3.11

WORKDIR /app

COPY ./streamlit_app/* .

# RUN pip install --no-cache-dir -r requirements.txt 
RUN pip install -r requirements.txt 
 
CMD ["streamlit", "run", "app.py"]
